TARGET = main
SRC = main.cpp Punteros.cpp Const.cpp Clases.cpp
CXX = g++
CXXFLAGS = -Wall -Wextra -g

all: $(TARGET)

$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) $(SRC) -o $(TARGET)

clean:
	rm -f $(TARGET)
