import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeInitializer } from "./_components/ChangeThemeButton";
import "./globals.css";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>SecureVault - Inicio</title>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </head>
      <body
        className={`antialiased ${inter.variable}`}
      >
        <ThemeInitializer></ThemeInitializer>
        {children}
      </body>
    </html>
  );
}
